apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: denisvoznik/petclinic:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: POSTGRES_URL
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1500m"
          ports:
            - containerPort: 8080
